syntax = "proto3";
package gogi.v1;

option go_package = "gogi/gogi/v1;gogiv1";

import "gogi/v1/llm_tool.proto";
import "gogi/v1/llm_message.proto";

service LLMModelServer {

  // Core inference
  rpc Run(LLMRunRequest) returns (LLMRunResponse);
  rpc RunStream(LLMRunRequest) returns (stream LLMStreamChunkResponse);

  // Discovery
  // list the llms the platform supports
  rpc ListLLMs(ListLLMsRequest) returns (ListLLMsResponse);
  // Get the LLM capabilities the platform supports
  rpc GetLLMCapabilities(GetLLMCapabilitiesRequest) returns (LLMCapabilitiesResponse);
  
  // get the providers supported by the platform
  rpc GetLLMProviders(GetLLMProvidersRequest) returns (LLMProvidersResponse);

  // Custom model registry
  // Register a user model
  rpc RegisterLLM(RegisterLLMRequest) returns (RegisterLLMResponse);
  
  // Get all the user registered models
  rpc ListRegisteredLLMs(ListRegisteredLLMsRequest) returns (ListRegisteredLLMsResponse);

  // Get the status of the LLM
  rpc GetLLMStatus(GetLLMStatusRequest) returns (LLMStatusResponse);

}


// Specifies how to call an LLM
message LLMRunRequestConfig{
    string model = 1;
    string provider = 2;
    float temperature = 3;
    int32 max_tokens = 4;
    float top_p = 5;
    repeated string stop_sequences = 6;
    float frequency_penalty = 7;
    float presence_penalty = 8;
    string system_prompt_name = 9;
}

message LLMRunRequest{
    repeated LLMMessage messages = 1;
    LLMRunRequestConfig config = 2;
    repeated ToolDefinition tools = 3;
    optional ResponseFormat response_format = 4;
}

message LLMRunResponse{

    string content = 1;
    string model = 2;
    string provider = 3;
    TokenUsage usage = 4;
    repeated ToolCall tool_calls = 5;
    string finish_reason = 6;

}

message LLMStreamChunkResponse{
    string token = 1;
    string model = 2;
    optional string finish_reason = 3;
    optional TokenUsage usage = 4;
}

message ListLLMsRequest{
  // TODO: Not all owners may have access to the models
}

message ListLLMsResponse{
  repeated ModelInfo models = 1;
}

message LLMCapabilities{
    int32 context_window = 1;
    bool supports_vision = 2;
    bool supports_tools = 3;
    bool supports_streaming = 4;
    bool supports_json_mode = 5;
}

message ModelInfo {
    string name = 1;
    string provider = 2;
    LLMCapabilities capabilities = 3;
}

message GetLLMCapabilitiesRequest{
  string model = 1;
}


message LLMCapabilitiesResponse{
    LLMCapabilities capabilities = 1;
}


message Provider{
  string name = 1;
  repeated string models = 2;
}

message GetLLMProvidersRequest{
   bool fetch_models = 1;
}

message LLMProvidersResponse{
	repeated Provider providers = 1;
}

message RegisterLLMRequest{
    ModelInfo info = 1;
    string endpoint = 2;
    string health_check = 3;
    string adapter_type = 4;
}

message RegisterLLMResponse{
    string name = 1;
    string status = 2;
    string  registered_at = 3;
}


message RegisteredLLM {
    ModelInfo info = 1;
    string endpoint = 2;
    string health_check = 3;
    string status = 4;
    string registered_at = 5;
    string adapter_type = 6;
}

message ListRegisteredLLMsRequest{
  // TODO: This may be per owner?
}

message ListRegisteredLLMsResponse{
  repeated RegisteredLLM models = 1;
}

message GetLLMStatusRequest{
 string name = 1;
}

message LLMStatusResponse{
  string name = 1;
    string status = 2;
    string last_checked = 3;
    string endpoint = 4;
}

// Function definition for LLM calls
//message LLMFunctionDefinition {
//    string name = 1;
//    string description = 2;
//    string parameters_json = 3;
//}
//
// Tool definition
//message ToolDefinition {
//    string type = 1;
//    LLMFunctionDefinition function = 2;
//}

//message ToolCall {
//    string id = 1;
//    string type = 2;
//    ToolCallFunction function = 3;
//}
//
//message ToolCallFunction {
//    string name = 1;
//    string arguments = 2;
//}

message ResponseFormat {
    string type = 1;
    string schema_json = 2;
}

// Token usage info struct
message TokenUsage {
    int32 prompt_tokens = 1;
    int32 completion_tokens = 2;
    int32 total_tokens = 3;
}


 
