syntax = "proto3";
package gogi.v1;

option go_package = "gogi/gogi/v1;gogiv1";

service PromptServer {

  // Register a new prompt
  rpc RegisterPrompt(PromptRegistrationRequest) returns (PromptRegistrationResponse);
  
  // Get a prompt
  rpc GetPrompt(PromptGetRequest) returns (PromptGetResponse);

  
  // Delete a specified prompt
  rpc Delete(PromptDeleteRequest) returns (PromptDeleteResponse);
 
}


message PromptTestInfo{
 string test_set_id = 1;
 string test_set_path = 2;
 map<string, double> metrics = 3;
}

message PromptParameters{
  double temperature = 1;
  int32 max_tokens = 2;
  repeated string stop_sequences = 3;
  double frequency_penalty = 4;
  double presence_penalty = 5;

}

message PromptMetadata{
 string author = 1;
 string model = 2;
 PromptParameters parameters = 3;
 PromptTestInfo test_info = 4;

}

message PromptRegistrationRequest{
 string prompt_name = 1;
 string prompt_version = 2;
 string gogi_index = 3;
 bytes content = 4;
 PromptMetadata metadata = 5;
}

message PromptGetResponse{
 string prompt_name = 1;
 string prompt_version = 2;
 string gogi_index = 3;
 bytes content = 4;
 PromptMetadata metadata = 5;
}

message PromptGetRequest{
 string gogi_index = 1;
 string prompt_name = 2;

}

message PromptDeleteRequest{
 string gogi_index = 1;
 string prompt_name = 2;

}

message PromptDeleteResponse{
  bool deleted = 1;
}
